// <auto-generated />
using Affinity.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Affinity.Migrations
{
    [DbContext(typeof(AffinityDbcontext))]
    partial class AffinityDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Affinity.Models.Edge", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color");

                    b.Property<int>("Direction");

                    b.Property<int>("First");

                    b.Property<string>("Name");

                    b.Property<int>("Second");

                    b.Property<int>("Weight");

                    b.HasKey("ID");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("Affinity.Models.Vertex", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color");

                    b.Property<string>("Name")
                        .HasMaxLength(8);

                    b.Property<int>("XPos");

                    b.Property<int>("YPos");

                    b.HasKey("ID");

                    b.ToTable("Vertices");
                });

            modelBuilder.Entity("Affinity.Models.VertexEdge", b =>
                {
                    b.Property<int>("VertexID");

                    b.Property<int>("EdgeID");

                    b.HasKey("VertexID", "EdgeID");

                    b.HasIndex("EdgeID");

                    b.ToTable("VertexEdges");
                });

            modelBuilder.Entity("Affinity.Models.VertexEdge", b =>
                {
                    b.HasOne("Affinity.Models.Edge", "Edge")
                        .WithMany("VertexEdges")
                        .HasForeignKey("EdgeID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Affinity.Models.Vertex", "Vertex")
                        .WithMany("VertexEdges")
                        .HasForeignKey("VertexID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
